# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2

jobs:
  
workflows:
  example-workflow:
    jobs:
      - example-job